//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoiffeurAppointmentSystem.ORM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<appointment> appointments { get; set; }
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<district> districts { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<gender> genders { get; set; }
        public virtual DbSet<person> people { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<service> services { get; set; }
        public virtual DbSet<work> works { get; set; }
        public virtual DbSet<workplace> workplaces { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
